- name: "Set superset config configured."
  template: src=config.py.j2 dest={{ superset_python_path }}/site-packages/superset/config.py
  notify:
    - restart superset

- name: Create an admin user.
  shell: "{{ superset_virtualenv_path }}/bin/fabmanager create-admin --app {{ superset_app }} --username {{ superset_username }} --firstname {{ superset_firstname }}  --lastname {{ superset_lastname }}  --email {{ superset_email }} --password {{ superset_pass }}"

- name: Superset init.
  shell: "{{ superset_virtualenv_path }}/bin/superset db upgrade && {{ superset_virtualenv_path }}/bin/superset load_examples && {{ superset_virtualenv_path }}/bin/superset init"

- name: Create superset systemd service
  template:
    src: "superset.service.j2"
    dest: "{{ superset_service }}"
    owner: root
    group: root
    mode: 644
  notify:
    - reload systemctl
    - restart superset

- name: Ensure Superset is running
  service: name=superset state=started enabled=yes

- name: Ensure Superset is restarted
  service: name=superset state=restarted
  when: superset_force_restart

