---
- name: Ensure dependencies are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-pip
    - python-dev

- name: Install virtualenv via pip
  pip:
    name: "{{ item }}"
    executable: pip
  with_items:
    - virtualenv
