---
- name: Create superset group.
  group:
    name: "{{ superset_group }}"

- name: Create superset user.
  user:
    name: "{{ superset_user }}"
    group: "{{ superset_group }}"
    shell: "{{ superset_shell }}"
    home: "{{ superset_home }}"
    create_home: yes

- include_tasks: "install-{{ superset_python_executable }}.yml"

- name: Ensure dependencies are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - libsasl2-dev
    - libldap2-dev
    - libmysqlclient-dev

- name: Delete the Superset virtualenv directory
  file:
    state: absent
    path: "{{ superset_virtualenv_path }}"
  when: superset_recreate_virtualenv

- name: Make sure the Superset virtualenv directory exists
  file:
    state: directory
    path: "{{ superset_virtualenv_path }}"
    owner: "{{ superset_user }}"
    group: "{{ superset_group }}"
    recurse: yes

- name: Install dependent pip libraries
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"
  with_items:
    - setuptools
    - psycopg2-binary
    - mysql
    - Flask-OAuthlib

- postgresql_db:
    login_host: "{{ superset_postgres_db_host }}"
    login_user: "{{ superset_postgres_login_user }}"
    login_password: "{{ superset_postgres_login_password }}"
    name: "{{ superset_postgres_db_name }}"
  tags: [ database ]

- postgresql_user:
    login_host: "{{ superset_postgres_db_host }}"
    login_user: "{{ superset_postgres_login_user }}"
    login_password: "{{ superset_postgres_login_password }}"
    db: "{{ superset_postgres_db_name }}"
    name: "{{ superset_postgres_db_user }}"
    password: "{{ superset_postgres_db_pass }}"
  tags: [ database ]

- name: Install superset
  pip:
    name: superset
    version: "{{ superset_version }}"
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"

- name: Make sure the superset upload directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ superset_user }}"
    group: "{{ superset_group }}"
  with_items:
    - "{{ superset_img_upload_dir }}"
    - "{{ superset_upload_dir }}"
