---
- name: Add a Python 3.6 PPA
  apt_repository:
    repo: "ppa:jonathonf/python-3.6"
    state: present

- name: Ensure dependencies are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python3.6
    - python3.6-dev
    - python3-pip

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
